import os
import io
import tempfile
from fpdf import FPDF
from pypdf import PdfWriter, PdfReader

class ReportCover(FPDF):
    def header(self):
        # Colorful Header
        self.set_fill_color(99, 102, 241) # #6366f1
        self.rect(0, 0, 210, 30, 'F')
        self.set_font('Arial', 'B', 20)
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, 'TutorPro Daily Portfolio', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, 'Generated by TutorPro Daily', 0, 0, 'C')

def generate_daily_report_pdf(student_name, date, category, set_num, remarks, photo_path, pdf_path):
    """
    Generates a cover page with the photo and remarks, then appends the provided pdf_path.
    Returns the final merged PDF as bytes.
    """
    # 1. Generate Cover Page
    pdf = ReportCover()
    pdf.add_page()
    
    # Title section
    pdf.set_font('Arial', 'B', 16)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 10, f'Student: {student_name}', 0, 1)
    
    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 8, f'Date: {date}', 0, 1)
    pdf.cell(0, 8, f'Category: {category}', 0, 1)
    pdf.cell(0, 8, f'Set / Level: {set_num}', 0, 1)
    pdf.ln(5)
    
    # Remarks
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 10, "Teacher's Remarks:", 0, 1)
    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 8, remarks)
    pdf.ln(10)
    
    # Photo
    if photo_path and os.path.exists(photo_path):
        pdf.set_font('Arial', 'B', 14)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 10, "Student Work / Photo:", 0, 1)
        # Try to constrain the image size nicely
        # Assuming maximum width of 190mm (210 - 20 margins)
        try:
            pdf.image(photo_path, x=10, w=190)
        except Exception as e:
            pdf.set_font('Arial', 'I', 10)
            pdf.set_text_color(255, 0, 0)
            pdf.cell(0, 10, f"Error loading image: {str(e)}", 0, 1)
    
    # Save cover page to temp buffer
    cover_pdf_bytes = bytes(pdf.output())
    
    # 2. Merge with Worksheet PDF if it exists
    merger = PdfWriter()
    
    cover_stream = io.BytesIO(cover_pdf_bytes)
    merger.append(cover_stream)
    
    if pdf_path and os.path.exists(pdf_path):
        try:
            merger.append(pdf_path)
        except Exception as e:
            pass # Silently fail appending if PDF is corrupt to still return cover
            
    # 3. Output Final Merged PDF
    final_output = io.BytesIO()
    merger.write(final_output)
    merger.close()
    
    return final_output.getvalue()

